# Generated by Django 2.2.9 on 2020-01-19 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='relation',
        ),
        migrations.AddField(
            model_name='connection',
            name='relation_type',
            field=models.CharField(blank=True, choices=[('grand_prent', 'Grand Parent'), ('parent', 'Parent'), ('children', 'Children'), ('sibling', 'Sibling'), ('cousin', 'Cousin')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='relations',
            field=models.ManyToManyField(through='family_tree.Connection', to='family_tree.People'),
        ),
    ]
