# Generated by Django 2.2.9 on 2020-01-20 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0002_auto_20200119_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='relation_type',
            field=models.CharField(blank=True, choices=[('grand_prent', 'Grand Parent of'), ('parent', 'Parent of'), ('children', 'Child of'), ('sibling', 'Sibling of'), ('cousin', 'Cousin of')], max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together={('people', 'relation_type', 'related_person')},
        ),
    ]
