# Generated by Django 2.2.9 on 2020-01-20 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0003_auto_20200120_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='relation_type',
            field=models.CharField(blank=True, choices=[('grand_parent', 'Grand Parent of'), ('parent', 'Parent of'), ('children', 'Child of'), ('sibling', 'Sibling of'), ('cousin', 'Cousin of'), ('spouse', 'Spouse of')], max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together={('people', 'related_person')},
        ),
    ]
